== notmuch vim ==

This is a vim plug-in that provides a fully usable mail client interface,
utilizing the notmuch framework.

== About this fork ==

This is my own fork of notmuch-vim. I have made a some updates and improvements from the upstream version:

 * updated to code to work with the latest version of Ruby mail (as of early 2021)
 * ported a few small fixes by Ian Main and Franz Fellner from the main notmuch repo (https://git.notmuchmail.org/git?p=notmuch;a=tree;f=vim;hb=HEAD)
 * merged a patch by Ian Main for viewing and saving attachments (https://notmuchmail.org/pipermail/notmuch/2014/019142.html)
 * set reasonable names for folder, search, and message buffers
 * ability to jump to previous message in a thread (bound to Shift+TAB by default)

== Install ==

Simply run 'make install'. However, check that you have the depencies below.

=== vim +ruby ===

Make sure your vim version has ruby support: check for +ruby in 'vim --version'
features.

 % vim --version | grep +ruby

=== ruby bindings ===

Check if you are able to run the following command cleanly:

 % ruby -e "require 'notmuch'"

If you don't see any errors, it means it's working and you can go to the next
section.

If it's not, you would need to compile it. An easy way to do that is by
downloading notmuch's source code:

 % git clone --branch=0.15.2 git://notmuchmail.org/git/notmuch ~/notmuch

And then:

 % make build notmuch=~/notmuch

(Note: you need to specify the notmuch source directory)

=== mail gem ===

Since libnotmuch library concentrates on things other than handling mail, we
need a library to do that, and for Ruby the best library for that is called
'mail'. The easiest way to install it is with ruby's gem. In most distro's the
package is called 'rubygems'.

Once you have gem, run:

 % gem install mail

In some systems gems are installed on a per-user basis by default, so make sure
you are running as the same user as the one that installed them.

This gem is not mandatory, but it's extremely recommended.

== Running ==

Simple:

 % gvim -c ':NotMuch'

You might want to write a wrapper script (e.g. `vnm`)

 #!/bin/sh
 gvim -c ":NotMuch $*"

So you can run:

 vnm is:inbox date:yesterday..

Enjoy ;)

== More stuff ==

As an example to configure a key mapping to add the tag 'to-do' and archive,
this is what I use:

----
let g:notmuch_rb_custom_search_maps = {
	\ 't':		'search_tag("+to-do -inbox")',
	\ }

let g:notmuch_rb_custom_show_maps = {
	\ 't':		'show_tag("+to-do -inbox")',
	\ }
----
